### ISSUE TITLE
Wrong resolution for Philips BDM3270 (PHL08E7)

### ISSUE THREAD

**Issue by giampierosalvi** [linuxhw/EDID#1]
Hi,
the Philips BDM3270 supports 2560x1440 at 60Hz, but in your list it says it does only 1920x1080. Below I paste the output of "sudo get-edid | parse-edid", where you can see that "Mode 0" is indeed 2560x1440. Is it possible to fix this? I am willing to help, if needed.

Thank you,
Giampiero

    This is read-edid version 3.0.2. Prepare for some fun.
    Attempting to use i2c interface
    No EDID on bus 0
    No EDID on bus 1
    No EDID on bus 2
    No EDID on bus 4
    No EDID on bus 5
    No EDID on bus 6
    No EDID on bus 7
    1 potential busses found: 3
    256-byte EDID successfully retrieved from i2c bus 3
    Looks like i2c was successful. Have a good day.
    Checksum Correct

    Section "Monitor"
        Identifier "PHL BDM3270"
        ModelName "PHL BDM3270"
        VendorName "PHL"
        # Monitor Manufactured week 52 of 2015
        # EDID version 1.3
        # Digital Display
        DisplaySize 710 400
        Gamma 2.20
        Option "DPMS" "true"
        Horizsync 15-99
        VertRefresh 23-76
        # Maximum pixel clock is 300MHz
        #Not giving standard mode: 1920x1080, 60Hz
        #Not giving standard mode: 1280x1024, 60Hz
        #Not giving standard mode: 1280x960, 60Hz
        #Not giving standard mode: 1440x900, 75Hz
        #Not giving standard mode: 1440x900, 60Hz
        #Not giving standard mode: 1680x1050, 60Hz
        #Not giving standard mode: 1280x720, 60Hz

        #Extension block found. Parsing...
        Modeline    "Mode 16" 148.50 1920 2448 2492 2640 1080 1089 1095 1125 -hsync -vsync 
        Modeline    "Mode 0" 241.50 2560 2608 2640 2720 1440 1443 1448 1481 +hsync +vsync 
        Modeline    "Mode 1" 25.200 640 656 752 800 480 490 492 525 -hsync -vsync
        Modeline    "Mode 2" 27.027 720 736 798 858 480 489 495 525 -hsync -vsync
        Modeline    "Mode 3" 27.027 720 736 798 858 480 489 495 525 -hsync -vsync
        Modeline    "Mode 4" 74.250 1920 2008 2052 2200 1080 1082 1087 1125 +hsync +vsync interlace
        Modeline    "Mode 5" 27.027 1440 1478 1602 1716 480 484 487 525 -hsync -vsync interlace
        Modeline    "Mode 6" 27.027 1440 1478 1602 1716 480 484 487 525 -hsync -vsync interlace
        Modeline    "Mode 7" 148.500 1920 2008 2052 2200 1080 1084 1089 1125 +hsync +vsync
        Modeline    "Mode 8" 27.000 720 732 796 864 576 581 586 625 -hsync -vsync
        Modeline    "Mode 9" 27.000 720 732 796 864 576 581 586 625 -hsync -vsync
        Modeline    "Mode 10" 74.250 1280 1720 1760 1980 720 725 730 750 +hsync +vsync
        Modeline    "Mode 11" 74.250 1920 2448 2492 2640 1080 1082 1089 1125 +hsync +vsync interlace
        Modeline    "Mode 12" 27.000 1440 1464 1590 1728 576 578 581 625 -hsync -vsync interlace
        Modeline    "Mode 13" 27.000 1440 1464 1590 1728 576 578 581 625 -hsync -vsync interlace
        Modeline    "Mode 14" 148.500 1920 2448 2492 2640 1080 1084 1089 1125 +hsync +vsync
        Modeline    "Mode 15" 74.250 1280 1390 1420 1650 720 725 730 750 +hsync +vsync
        Modeline    "Mode 17" 74.25 1920 2008 2052 2200 540 542 547 562 +hsync +vsync interlace
        Modeline    "Mode 18" 74.25 1920 2448 2492 2640 540 542 547 562 +hsync +vsync interlace
        Modeline    "Mode 19" 74.25 1280 1720 1760 1980 720 725 730 750 +hsync +vsync 
        Option "PreferredMode" "Mode 16"
    EndSection

**Comment by lvc** [comment]
Hi,

Thank you for the report.

Could you please create a hardware probe of your computer? This will help me to debug the case properly.

Probably there is a difference in some bits of your EDID and the one previously registered in the database (i.e. model name is the same but settings are different). For this reason I compute the 'ID' of the monitor as MD5 of EDID binary.

https://github.com/linuxhw/hw-probe#usage

**Comment by linuxhw** [comment]
Fixed by the commit https://github.com/linuxhw/hw-probe/commit/1cd12faccb71cad8ddde8444a374c7af0d9ae067.

Thank you!

**Comment by giampierosalvi** [comment]
...by the way, I managed to make it work with the following (in the meantime I had moved the monitor to HDMI1 instead of HDMI2, but that did not change anything):

xrandr --newmode "2560x1440" 241.50 2560 2608 2640 2720 1440 1443 1448 1481 +hsync +vsync 
xrandr --addmode HDMI1 2560x1440
xrandr --output HDMI1 --mode 2560x1440

However, it would be great if the monitor native resolution was detected automatically.

Thanks again

**Comment by lvc** [comment]
Hi,

I've fixed only detector of the best resolution in the hw-probe tool, not the system's configure scripts for monitors.

Looks like your graphics driver failed to detect best resolution. What is your probe ID or graphics card model and kernel version?

Thank you.

**Comment by lvc** [comment]
Please forget my last comment. You just need to connect by DisplayPort instead of HDMI to get best resolution automatically.
