### ISSUE TITLE
Linux begginer question

### ISSUE THREAD

**Issue by HoolianKaracks** [linuxhw/EDID#12]
I think all of you are very good for using linux, so nobody encountered my problem.

I just want to earn some monitor edid bin file but I dont know how to use below command line.

Can you guys explain to me for begginer of Linux? I already put the my target edid fild on current directory and typed this below command line but not working. I changed edid file to .txt file for this. they are complaining "'[:space:]' " is wrong. and I already changed to '[[:space:]]' like they advised. but not working.

cat EDID.txt | grep -E '^([a-f0-9]{32}|[a-f0-9 ]{47}) | tr -d '[:space:]' | xxd -r -p > EDID.bin

**Comment by linuxhw** [comment]
What is your Linux distro?

**Comment by HoolianKaracks** [comment]
ubuntu. I solved problem by using edid-rw by import txt file(not bin file) and edited edid but failed maybe my lcd is edid protected. anyway thanks for answering.

**Comment by linuxhw** [comment]
The problem was in the command line (missed closing quote in the grep part). I've fixed it to:

    cat EDID.txt | grep -E '^([a-f0-9]{32}|[a-f0-9 ]{47})$' | tr -d '[:space:]' | xxd -r -p > EDID.bin

Thank you!
