### ISSUE TITLE
duplicate EDID with wrong ID and filename

### ISSUE THREAD

**Issue by joevt** [linuxhw/EDID#13]
I was looking at the EDIDs and found a mismatch between filename and ID.

```
IFS=$'\n'
for thefile in $(grep -l -R 'edid-decode' Analog Digital); do
	name=$(basename "$thefile")
	ID=$(egrep -E '^([a-f0-9]{32}|[a-f0-9 ]{47})$' "$thefile" | tr -d ' \n' | md5 | sed -E 's/(.{12}).*/\1/' | tr 'abcdef' 'ABCDEF')
	if [[ $name != $ID ]]; then
		echo "# mismatch $ID:$thefile"
	fi
done
```

The result:
`# mismatch 82A320A8FBD0:Digital/Chi Mei Optoelectronics/CMO1800/EA3921B8A7CD`

It appears that
`Digital/Chi Mei Optoelectronics/CMO1800/EA3921B8A7CD` is a duplicate of
`Digital/Chi Mei Optoelectronics/CMO1800/82A320A8FBD0` and should be removed.

EA3921B8A7CD is mentioned in #7

**Comment by linuxhw** [comment]
Fixed. Thank you!
