### ISSUE TITLE
In the index the resolution of HP ZR24w is wrong

### ISSUE THREAD

**Issue by Icenowy** [linuxhw/EDID#2]
HP ZR24w is 1920x1200, and this is shown as a custom mode in the EDID infomation. However in DigitalDisplay.md it's tagged as 1920x1080.

**Comment by linuxhw** [comment]
Fixed by the commit https://github.com/linuxhw/hw-probe/commit/1cd12faccb71cad8ddde8444a374c7af0d9ae067

Thanks a lot!
