### ISSUE TITLE
Regenerate with -c --skip-sha flags

### ISSUE THREAD

**Issue by ValZapod** [linuxhw/EDID#8]
@linuxhw Oops, I failed to mention to use -c --skip-sha flags with edid-decode will actually report any conformity issues with the EDID.

Also, the author and me looked into the db and managed to fix some parsing issues of HDMI 2.0 block (VRRmin and VRRmax in particular)...

_Originally posted by @ValZapod in https://github.com/linuxhw/EDID/issues/5#issuecomment-618466551_

**Comment by bsdhw** [comment]
Fixed by commit 093fa862ec54bc2698a4b90570487a902438bb86

Thanks.

**Comment by ValZapod** [comment]
Wait a second, while most of files did not get the it like this? https://github.com/linuxhw/EDID/blob/master/Analog/Relisys/TEU02CB/8AB611EFCF1D

**Comment by bsdhw** [comment]
Right command to regenerate the repository:

    find . -type f -regextype posix-extended -regex '.*/[A-F0-9]{12}$' -print0 | while read -r -d '' file; do cat "$file" | grep -E '^([a-f0-9]{32}|[a-f0-9 ]{47})$' | edid-decode-2020-06-13 -c --skip-sha > /tmp/file; cat /tmp/file > "$file"; done

**Comment by bsdhw** [comment]
Fixed by commit 16bc0afe546b07752d71bd7fb4ba0cecd763830f.

EDIDs with conformity failures were missed.

**Comment by ValZapod** [comment]
Yep. Looks like 8,024 are good and 15,608 are non-conformat. Heh.

**Comment by ValZapod** [comment]
@bsdhw Another update: fix for segfault here https://github.com/linuxhw/EDID/blob/master/Digital/Others/UGD1106/E77880113EDC fix for DTD 6 here: https://github.com/linuxhw/EDID/blob/master/Digital/Ancor%20Communications/ACI24FA/3A493470F369 (fixed by https://github.com/ValZapod/edid-decode/commit/c0e41332af7a18db2b776ad1d7a84c59a44da41b) and other fixes, like this one https://github.com/ValZapod/edid-decode/commit/34d94b492a9e422ff4701be67231d58bb92604d8

**Comment by linuxhw** [comment]
Regenerated by edid-decode 34d94b492a 2020-10-15.

Thanks!
